image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/k8s
  TF_STATE_NAME: ${CI_COMMIT_BRANCH}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}
  AWS_ACCESS_KEY_ID: ${TF_VAR_aws_access_key_id}
  AWS_SECRET_ACCESS_KEY: ${TF_VAR_aws_secret_access_key}
  TF_VAR_cloudflare_api_key: ${TF_VAR_cloudflare_api_key}
  TF_VAR_cloudflare_email: ${TF_VAR_cloudflare_email}
  TF_VAR_k8s_name: k8s-${CI_COMMIT_BRANCH}
  VALIDATE: "yes"
  PHASE: "apply"

cache:
  key: ${CI_COMMIT_BRANCH}-cache
  paths:
    - ${TF_ROOT}/.terraform

stages:
  - init
  - validate
  - build
  - apply
  - destroy

before_script:
  - cd ${TF_ROOT}
  - echo ${TF_ADDRESS}

# https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_state.html#configure-the-backend
.terraform-init: &terraform-init
  - gitlab-terraform init

terraform init:
  stage: init
  script:
    - *terraform-init

terraform validate:
  stage: validate
  script:
    - gitlab-terraform validate
  only:
    variables:
      - $VALIDATE == "yes"

terraform build:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  only:
    variables:
      - $PHASE == "apply"
  environment:
    name: ${CI_COMMIT_BRANCH}

terraform apply:
  stage: apply
  script:
    - gitlab-terraform apply
  only:
    variables:
      - $PHASE == "apply"
  dependencies:
    - terraform build
  when: manual
  environment:
    name: ${CI_COMMIT_BRANCH}

terraform destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy
  only:
    variables:
      - $PHASE == "apply"
  when: manual
  environment:
    name: ${CI_COMMIT_BRANCH}
