version: '3.1'
services:

  db:
    image: mariadb:10.7.1
    environment:
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysql" ,"$MARIADB_DATABASE", "-h", "localhost", "-P", "3306", "-u", "$MARIADB_USER", "-p$MARIADB_PASSWORD", "-e", "SELECT 1"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 1s
# connect from localhost: mysql --protocol=tcp $MARIADB_DATABASE -u$MARIADB_USER -p$MARIADB_PASSWORD


  goose:
    depends_on:
      db:
        condition: service_healthy

    build: app/backend
    environment:
      - GOOSE_DRIVER=mysql
      - GOOSE_DBSTRING=$MARIADB_USER:$MARIADB_PASSWORD@tcp(db:3306)/$MARIADB_DATABASE
    command: ["goose", "up"]
