"aws":
  "hosts":
    "gitlab":
      "ansible_host": "gitlab.ubukubu.ru"
      "ansible_port": "8822"
      "ansible_user": "ubuntu"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"
    "efs_dnsname": "fs-06a338943ed6fd8f3.efs.eu-central-1.amazonaws.com"
    "efs_id": "fs-06a338943ed6fd8f3"
    "efs_port": "2049"


