"aws":
  "hosts":
    "gitlab":
      "ansible_host": "lab.ubukubu.ru"
      "ansible_port": "8822"
      "ansible_user": "ubuntu"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"
    "efs_dnsname": "fs-04c951ca5e2cc810f.efs.eu-central-1.amazonaws.com"
    "efs_id": "fs-04c951ca5e2cc810f"
    "efs_port": "2049"


