# app.settings.migrationDir: "migrations"
migration_dir: "/app/migrations"
app_endpoint: "0.0.0.0:5000"
# app.dbSettings.Host: "localhost"
db_host: "db"
db_name: "covid19"
db_port: "3306"
db_user: "covid19"
db_pass: "Johtae5j"
data_reset: true
