---

- hosts:
  - gitlab

  vars:
    domain_name: "{{ ansible_host }}"
    letsencrypts_email: sergei_chulanov@epam.com
    efs_user: "{{ ansible_user }}"
    efs_mountpath: /mnt/efs
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_users:
      - "{{ ansible_user }}"
    pip_install_packages:
      - name: docker
    remove_gitlab_data: false # only false or true

  roles:
    - { role: common, tags: common }
    - { role: debug, tags: debug }
    - { role: efs, tags: efs }
    - { role: geerlingguy.pip, tags: pip, become: yes }
    - { role: geerlingguy.docker, tags: docker, become: yes }
    - { role: gitlab, tags: gitlab }
    - { role: nginx, tags: nginx }
    - { role: letsencrypt, tags: letsencrypt }
