---
- name: Actions who are needed become
  block:

    - name: Ensure mountpoint is created
      ansible.builtin.file:
        path: "{{ efs_mountpath }}"
        owner: "{{ efs_user }}"
        group: "{{ efs_user }}"
        mode: '0700'
        state: directory
    
    - name: Ensure dependencies are installed
      ansible.builtin.apt:
        name: nfs-common
        state: present
    
    - name: Ensure EFS volume is mounted
      ansible.posix.mount:
        src: "{{ efs_dnsname }}:/"
        path: "{{ efs_mountpath }}"
        fstype: nfs
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
        state: mounted
        fstab: /etc/fstab
  become: yes
